// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: address_queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
        id,
        address,
        number,
        street,
        city,
        state,
        postal_code,
        country,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, address, street, city, state, postal_code, country, number, created_at, updated_at
`

type CreateAddressParams struct {
	ID         pgtype.UUID
	Address    pgtype.Text
	Number     pgtype.Text
	Street     pgtype.Text
	City       pgtype.Text
	State      pgtype.Text
	PostalCode pgtype.Text
	Country    pgtype.Text
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ID,
		arg.Address,
		arg.Number,
		arg.Street,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
		arg.CreatedAt,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Street,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.Country,
		&i.Number,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
