// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: address_queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
        address,
        number,
        street,
        city,
        state,
        postal_code,
        country
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateAddressParams struct {
	Address    pgtype.Text
	Number     pgtype.Text
	Street     pgtype.Text
	City       pgtype.Text
	State      pgtype.Text
	PostalCode pgtype.Text
	Country    pgtype.Text
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.Address,
		arg.Number,
		arg.Street,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Country,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
