// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package database

import (
	"database/sql"
)

type Address struct {
	ID      int32
	ZipCode string
	Address string
	Street  string
	State   string
	City    string
}

type User struct {
	ID             string
	Name           string
	Lastname       string
	Email          int32
	DocumentType   string
	DocumentNumber string
	AddressID      sql.NullInt32
}
