// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         pgtype.UUID
	Address    pgtype.Text
	Street     pgtype.Text
	City       pgtype.Text
	State      pgtype.Text
	PostalCode pgtype.Text
	Country    pgtype.Text
	Number     pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Company struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	Document  pgtype.Text
	AddressID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CompanyUser struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type ContactInfo struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Image struct {
	ID          pgtype.UUID
	Description pgtype.Text
	Url         pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Permission struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type Role struct {
	ID          pgtype.UUID
	Name        string
	Description string
}

type RolesPermission struct {
	ID           pgtype.UUID
	RoleID       pgtype.UUID
	PermissionID pgtype.UUID
}

type Store struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	Name      string
	Document  string
	AddressID pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type StoreUser struct {
	ID        pgtype.UUID
	StoreID   pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type TemplateEmail struct {
	ID          pgtype.UUID
	Name        string
	Url         string
	Description string
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID             pgtype.UUID
	Name           pgtype.Text
	Email          string
	Document       string
	Password       pgtype.Text
	MobilePhone    pgtype.Text
	Active         pgtype.Bool
	RegisterToken  pgtype.Text
	TokenExpiresAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	AddressID      pgtype.UUID
	ImageID        pgtype.UUID
}

type UsersPermission struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	PermissionID pgtype.UUID
}

type UsersRole struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	RoleID pgtype.UUID
}
