version: '3.1'

networks:
  invetory-management-api:
    driver: 
      bridge
    ipam:
      config:
        - subnet: 172.168.0.0/16
          gateway: 172.168.0.1

services:
  db:
    container_name: inventory-management-db
    image: postgres:15.3
    restart: always
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=inventory_management
    networks:
      - invetory-management-api


   
volumes:
  postgres-data:

