CREATE TABLE roles (
    id CHAR(36) PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL
);

ALTER TABLE users ADD COLUMN role_id VARCHAR(255) REFERENCES roles(id);
