// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID         int    `json:"id"`
	Address    string `json:"address"`
	Street     string `json:"street"`
	Number     string `json:"number"`
	City       string `json:"city"`
	State      string `json:"state"`
	Country    string `json:"country"`
	PostalCode string `json:"postalCode"`
	UserID     string `json:"userId"`
}

type ContactInfo struct {
	ID    string `json:"id"`
	Name  string `json:"Name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type Login struct {
	Token string `json:"token"`
}

type Message struct {
	Message string `json:"message"`
}

type NewAddress struct {
	Address    string  `json:"address"`
	Street     *string `json:"street,omitempty"`
	Number     *string `json:"number,omitempty"`
	City       string  `json:"city"`
	State      string  `json:"state"`
	Country    string  `json:"country"`
	PostalCode string  `json:"postalCode"`
	UserID     string  `json:"userId"`
}

type NewContactInfo struct {
	Name  string `json:"Name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type NewLogin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewPermission struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewPreUser struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	Status string `json:"status"`
}

type NewRole struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewRolePermission struct {
	RoleID       string `json:"roleId"`
	PermissionID string `json:"permissionId"`
}

type NewUser struct {
	Name           string `json:"name"`
	Email          string `json:"email"`
	Phone          string `json:"phone"`
	DocumentType   string `json:"document_type"`
	DocumentNumber string `json:"document_number"`
}

type NewUserComplete struct {
	Phone          string `json:"phone"`
	Password       string `json:"password"`
	DocumentType   string `json:"document_type"`
	DocumentNumber string `json:"document_number"`
	RegisterToken  string `json:"RegisterToken"`
}

type Permissions struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type PreUser struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type RolePermissions struct {
	ID           string `json:"id"`
	RoleID       string `json:"roleId"`
	PermissionID string `json:"permissionId"`
}

type Roles struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type User struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	Email          string   `json:"email"`
	Phone          string   `json:"phone"`
	DocumentType   string   `json:"document_type"`
	DocumentNumber string   `json:"document_number"`
	Address        *Address `json:"address"`
}
